// Auto-generated by Morpheus DSL Compiler
// Do not edit manually

export interface Quantity<Unit extends string> {
  value: number;
  unit: Unit;
}

export interface Person {
  name: string;
  age: number;
}

export interface PersonDTO {
  fullName: string;
  ageYears: number;
}
