// Auto-generated by Morpheus DSL Compiler
// Do not edit manually

export interface Quantity<Unit extends string> {
  value: number;
  unit: Unit;
}

// Quantity type guard
export function isQuantity(value: any): value is Quantity<any> {
  return typeof value === 'object' && value !== null && 'value' in value && 'unit' in value;
}

// Quantity arithmetic operations
export function multiplyValue(a: any, b: any): any {
  if (isQuantity(a) && isQuantity(b)) {
    // Quantity * Quantity - unit multiplication would require unit system
    // For now, return a Quantity with combined unit name
    return { value: a.value * b.value, unit: `${a.unit}_times_${b.unit}` };
  } else if (isQuantity(a)) {
    // Quantity * scalar
    return { value: a.value * b, unit: a.unit };
  } else if (isQuantity(b)) {
    // scalar * Quantity
    return { value: a * b.value, unit: b.unit };
  } else {
    // scalar * scalar
    return a * b;
  }
}

export function divideValue(a: any, b: any): any {
  if (isQuantity(a) && isQuantity(b)) {
    return { value: a.value / b.value, unit: `${a.unit}_per_${b.unit}` };
  } else if (isQuantity(a)) {
    return { value: a.value / b, unit: a.unit };
  } else if (isQuantity(b)) {
    return { value: a / b.value, unit: `per_${b.unit}` };
  } else {
    return a / b;
  }
}

export function addValue(a: any, b: any): any {
  if (isQuantity(a) && isQuantity(b)) {
    return { value: a.value + b.value, unit: a.unit };
  } else {
    return a + b;
  }
}

export function subtractValue(a: any, b: any): any {
  if (isQuantity(a) && isQuantity(b)) {
    return { value: a.value - b.value, unit: a.unit };
  } else {
    return a - b;
  }
}

export interface FactoryProductionData {
  factoryId: string;
  month: string;
  productionVolume: number;
  operatingHours: number;
  electricityUsage: number;
  naturalGasUsage: number;
  dieselFuelUsage: number;
  rawMaterialPurchased: number;
  packagingMaterialUsed: number;
  wasteGenerated: number;
  wasteRecycled: number;
  waterConsumption: number;
  employeeCount: number;
}

export interface GHGEmissionsReport {
  facilityIdentifier: string;
  reportingPeriod: Date;
  scope1DirectEmissions: number;
  scope1NaturalGas: number;
  scope1DieselCombustion: number;
  scope2IndirectEmissions: number;
  scope2Electricity: number;
  scope3OtherIndirect: number;
  scope3PurchasedGoods: number;
  scope3WasteDisposal: number;
  totalEmissions: number;
  emissionsPerUnit: number;
  emissionsPerHour: number;
  calculationMethodology: string;
  verified: boolean;
}

export interface SupplierEnvironmentalData {
  supplierId: string;
  supplierName: string;
  country: string;
  certifications: string;
  productCategory: string;
  carbonIntensity: number;
  renewableEnergyRatio: number;
  averageTransportDistance: number;
  primaryTransportMode: string;
  lastUpdated: Date;
}

export interface SustainabilityReport {
  organizationId: string;
  reportYear: number;
  totalGHGEmissions: number;
  ghgReductionFromBaseline: number;
  renewableEnergyPercentage: number;
  recyclingRate: number;
  wasteToLandfill: number;
  waterRecyclingRate: number;
  sustainableSourcingRatio: number;
  suppliersCertified: number;
  safetyIncidentRate: number;
  employeeTurnoverRate: number;
  regulatoryCompliance: boolean;
  auditedBy: string;
  publicationDate: Date;
}
